include("include/cmd.jl")

runcmd(
    string.([
        "--beta_bounds",
        0.2 / 4,
        6.68 / 4,
        "--gamma0",
        1 / 4,
        "--gamma_bounds",
        1 / 4,
        1 / 4,
        "--lambda0",
        1 / 14,
        "--lambda_bounds",
        1 / 14,
        1 / 14,
        "--alpha_bounds",
        0.005,
        0.05,
        "--locations",
        # union(keys(Covid19ModelVN.LOC_NAMES_US), keys(Covid19ModelVN.LOC_NAMES_VN))...,
        "losangeles_ca",
        "--train_days=45",
        "--spc_lag_days=0",
        "--loss_type=sse",
        "--loss_regularization=0.00001",
        "--savedir=testsnapshots/newmodel",
        "--show_progress",
        # "--multithreading",
        "fbmobility4",
        "train_growing_trajectory_two_stages",
        "--lr=0.05",
        "--lr_limit=0.0001",
        "--lr_decay_rate=0.7",
        "--lr_decay_step=200",
        "--maxiters_initial=500",
        "--maxiters_growth=0",
        "--maxiters_second=1000",
        "--tspan_size_initial=4",
        "--tspan_size_growth=4",
    ]),
)
