include("include/cmd.jl")

runcmd(
    string.([
        "--beta_bounds",
        0.2 / 4,
        6.68 / 4,
        "--gamma0",
        1 / 4,
        "--gamma_bounds",
        1 / 4,
        1 / 4,
        "--lambda0",
        1 / 14,
        "--lambda_bounds",
        1 / 14,
        1 / 14,
        "--alpha_bounds",
        0.005,
        0.05,
        "--locations",
        # union(keys(Covid19ModelVN.LOC_NAMES_US), keys(Covid19ModelVN.LOC_NAMES_VN))...,
        "harris_tx",
        "--train_days=45",
        "--spc_lag_days=0",
        "--loss_type=sse",
        "--loss_regularization=0.00001",
        "--savedir=testsnapshots/newmodel",
        "--show_progress",
        # "--multithreading",
        "fbmobility4",
        "train_whole_trajectory_two_stages",
        "--lr=0.05",
        "--lr_limit=0.0001",
        "--lr_decay_rate=0.1",
        "--lr_decay_step=10000",
        "--maxiters_first=30000",
        "--maxiters_second=10000",
        "--minibatching=7",
    ]),
)
